#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
RAレコードパーサー: ２．レース詳細

このファイルは自動生成されました。
Source: 公式JV-Data仕様書 Ver.4.9.0.1
Generated by: scripts/generate_all_parsers.py
"""

from typing import Dict, Optional
from src.utils.logger import get_logger


class RAParser:
    """
    RAレコードパーサー

    ２．レース詳細
    レコード長: 856 bytes
    VBテーブル名: RACE
    """

    RECORD_TYPE = "RA"
    RECORD_LENGTH = 1272

    def __init__(self):
        self.logger = get_logger(__name__)

    @staticmethod
    def decode_field(data: bytes) -> str:
        """バイトデータをデコードして文字列に変換"""
        try:
            # cp932でデコード、空白を除去
            return data.decode("cp932", errors="replace").strip()
        except Exception:
            return ""

    def parse(self, data: bytes) -> Optional[Dict[str, str]]:
        """
        RAレコードをパースしてフィールド辞書を返す

        Args:
            data: パース対象のバイトデータ

        Returns:
            フィールド名をキーとした辞書、エラー時はNone
        """
        try:
            # レコード長チェック
            if len(data) < self.RECORD_LENGTH:
                self.logger.warning(
                    f"RAレコード長不足: expected={self.RECORD_LENGTH}, actual={len(data)}"
                )
                # return None  # 短いレコードも許容する場合はコメントアウト

            # フィールド抽出
            result = {}

            # 1. レコード種別ID (位置:1, 長さ:2)
            result["RecordSpec"] = self.decode_field(data[0:2])

            # 2. データ区分 (位置:3, 長さ:1)
            result["DataKubun"] = self.decode_field(data[2:3])

            # 3. データ作成年月日 (位置:4, 長さ:8)
            result["MakeDate"] = self.decode_field(data[3:11])

            # 4. 開催年 (位置:12, 長さ:4)
            result["Year"] = self.decode_field(data[11:15])

            # 5. 開催月日 (位置:16, 長さ:4)
            result["MonthDay"] = self.decode_field(data[15:19])

            # 6. 競馬場コード (位置:20, 長さ:2)
            result["JyoCD"] = self.decode_field(data[19:21])

            # 7. 開催回[第N回] (位置:22, 長さ:2)
            result["Kaiji"] = self.decode_field(data[21:23])

            # 8. 開催日目[N日目] (位置:24, 長さ:2)
            result["Nichiji"] = self.decode_field(data[23:25])

            # 9. レース番号 (位置:26, 長さ:2)
            result["RaceNum"] = self.decode_field(data[25:27])

            # 10. 曜日コード (位置:28, 長さ:1)
            result["YoubiCD"] = self.decode_field(data[27:28])

            # 11. 特別競走番号 (位置:29, 長さ:4)
            result["TokuNum"] = self.decode_field(data[28:32])

            # 12. 競走名本題 (位置:33, 長さ:60)
            result["Hondai"] = self.decode_field(data[32:92])

            # 13. 競走名副題 (位置:93, 長さ:60)
            result["Fukudai"] = self.decode_field(data[92:152])

            # 14. 競走名カッコ内 (位置:153, 長さ:60)
            result["Kakko"] = self.decode_field(data[152:212])

            # 15. 競走名本題欧字 (位置:213, 長さ:120)
            result["HondaiEng"] = self.decode_field(data[212:332])

            # 16. 競走名副題欧字 (位置:333, 長さ:120)
            result["FukudaiEng"] = self.decode_field(data[332:452])

            # 17. 競走名カッコ内欧字 (位置:453, 長さ:120)
            result["KakkoEng"] = self.decode_field(data[452:572])

            # 18. 競走名略称10文字 (位置:573, 長さ:20)
            result["Ryakusyo10"] = self.decode_field(data[572:592])

            # 19. 競走名略称6文字 (位置:593, 長さ:12)
            result["Ryakusyo6"] = self.decode_field(data[592:604])

            # 20. 競走名略称3文字 (位置:605, 長さ:6)
            result["Ryakusyo3"] = self.decode_field(data[604:610])

            # 21. 競走名区分 (位置:611, 長さ:1)
            result["Kubun"] = self.decode_field(data[610:611])

            # 22. 重賞回次[第N回] (位置:612, 長さ:3)
            result["Nkai"] = self.decode_field(data[611:614])

            # 23. グレードコード (位置:615, 長さ:1)
            result["GradeCD"] = self.decode_field(data[614:615])

            # 24. 変更前グレードコード (位置:616, 長さ:1)
            result["GradeCDBefore"] = self.decode_field(data[615:616])

            # 25. 競走種別コード (位置:617, 長さ:2)
            result["SyubetuCD"] = self.decode_field(data[616:618])

            # 26. 競走記号コード (位置:619, 長さ:3)
            result["KigoCD"] = self.decode_field(data[618:621])

            # 27. 重量種別コード (位置:622, 長さ:1)
            result["JyuryoCD"] = self.decode_field(data[621:622])

            # 28. 競走条件コード 2歳条件 (位置:623, 長さ:3)
            result["JyokenCD1"] = self.decode_field(data[622:625])

            # 29. 競走条件コード 3歳条件 (位置:626, 長さ:3)
            result["JyokenCD2"] = self.decode_field(data[625:628])

            # 30. 競走条件コード 4歳条件 (位置:629, 長さ:3)
            result["JyokenCD3"] = self.decode_field(data[628:631])

            # 31. 競走条件コード 5歳以上条件 (位置:632, 長さ:3)
            result["JyokenCD4"] = self.decode_field(data[631:634])

            # 32. 競走条件コード 最若年条件 (位置:635, 長さ:3)
            result["JyokenCD5"] = self.decode_field(data[634:637])

            # 33. 競走条件名称 (位置:638, 長さ:60)
            result["JyokenName"] = self.decode_field(data[637:697])

            # 34. 距離 (位置:698, 長さ:4)
            result["Kyori"] = self.decode_field(data[697:701])

            # 35. 変更前距離 (位置:702, 長さ:4)
            result["KyoriBefore"] = self.decode_field(data[701:705])

            # 36. トラックコード (位置:706, 長さ:2)
            result["TrackCD"] = self.decode_field(data[705:707])

            # 37. 変更前トラックコード (位置:708, 長さ:2)
            result["TrackCDBefore"] = self.decode_field(data[707:709])

            # 38. コース区分 (位置:710, 長さ:2)
            result["CourseKubunCD"] = self.decode_field(data[709:711])

            # 39. 変更前コース区分 (位置:712, 長さ:2)
            result["CourseKubunCDBefore"] = self.decode_field(data[711:713])

            # 40. 本賞金 (位置:714, 長さ:8)
            result["Honsyokin1"] = self.decode_field(data[713:721])

            # 41. 変更前本賞金 (位置:722, 長さ:8)
            result["Honsyokin2"] = self.decode_field(data[721:729])

            # 42. 付加賞金 (位置:730, 長さ:8)
            result["Honsyokin3"] = self.decode_field(data[729:737])

            # 43. 変更前付加賞金 (位置:738, 長さ:8)
            result["Honsyokin4"] = self.decode_field(data[737:745])

            # 44. 発走時刻 (位置:746, 長さ:4)
            result["HassoTime"] = self.decode_field(data[745:749])

            # 45. 変更前発走時刻 (位置:750, 長さ:4)
            result["HassoTimeBefore"] = self.decode_field(data[749:753])

            # 46. 登録頭数 (位置:754, 長さ:2)
            result["TorokuTosu"] = self.decode_field(data[753:755])

            # 47. 出走頭数 (位置:756, 長さ:2)
            result["SyussoTosu"] = self.decode_field(data[755:757])

            # 48. 入線頭数 (位置:758, 長さ:2)
            result["NyusenTosu"] = self.decode_field(data[757:759])

            # 49. 天候コード (位置:760, 長さ:1)
            result["TenkoCD"] = self.decode_field(data[759:760])

            # 50. 芝馬場状態コード (位置:761, 長さ:1)
            result["SibaBabaCD"] = self.decode_field(data[760:761])

            # 51. ダート馬場状態コード (位置:762, 長さ:1)
            result["DirtBabaCD"] = self.decode_field(data[761:762])

            # 52. ラップタイム (位置:763, 長さ:3×25=75)
            lap_parts = []
            for i in range(25):
                chunk = self.decode_field(data[762 + i * 3: 762 + i * 3 + 3])
                if not chunk:
                    break
                try:
                    val = int(chunk)
                    if val == 0:
                        break
                    lap_parts.append(f"{val / 10:.1f}")
                except ValueError:
                    break
            result["LapTime"] = "-".join(lap_parts)

            # 53. 障害マイルタイム (位置:838, 長さ:4)
            result["SyogaiMileTime"] = self.decode_field(data[837:841])

            # 54. 前3ハロン (位置:842, 長さ:3)
            result["Haron3F"] = self.decode_field(data[841:844])

            # 55. 前4ハロン (位置:845, 長さ:3)
            result["Haron4F"] = self.decode_field(data[844:847])

            # 56. 後3ハロン (位置:848, 長さ:3)
            result["Haron3L"] = self.decode_field(data[847:850])

            # 57. 後4ハロン (位置:851, 長さ:3)
            result["Haron4L"] = self.decode_field(data[850:853])

            # 58. <コーナー通過順位> (位置:854, 長さ:0)
            # Note: This is a section header with 0 length, not an actual field

            # 59. 　　コーナー (位置:854, 長さ:1)
            result["Corner"] = self.decode_field(data[853:854])

            # 60. 　　周回数 (位置:855, 長さ:1)
            result["Syukaisu"] = self.decode_field(data[854:855])

            # 61. 　　各通過順位 (位置:856, 長さ:70)
            result["TsukaJyuni"] = self.decode_field(data[855:925])

            # 62. レコード更新区分 (位置:926, 長さ:1)
            result["RecordUpKubun"] = self.decode_field(data[925:926])

            # 63. レコード区切 (位置:927, 長さ:2)
            result["Crlf"] = self.decode_field(data[926:928])

            return result

        except Exception as e:
            self.logger.error(f"RAレコードパース中にエラー: {e}")
            return None
